# Generated by Django 3.1.4 on 2020-12-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processor',
            new_name='Anime',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='processor_id',
            new_name='anime_id',
        ),
    ]
